# Generated by Django 4.1.5 on 2023-01-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roupas',
            new_name='Roupa',
        ),
    ]
