# Generated by Django 4.1.5 on 2023-01-02 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_rename_roupas_roupa'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='tamanho',
            field=models.CharField(choices=[('Pequeno', 'P'), ('Médio', 'M'), ('Grande', 'G'), ('Extra Grande', 'GG')], max_length=20),
        ),
    ]
